# Generated by Django 5.1 on 2025-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_events', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=50)),
                ('skills_required', models.CharField(max_length=100, null=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='applied_student', to='accounts.studentprofile')),
            ],
        ),
    ]
