# Generated by Django 5.1 on 2025-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementmanagement',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placementmanagement',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placementmanagement',
            name='package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placementmanagement',
            name='skills_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
