# Generated by Django 5.1 on 2025-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_facultyprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='marks',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
